name: Keep Repository Active

on:
  schedule:
#    - cron: '0 0 */50 * *'  # Runs every 50 days at midnight UTC
     - cron: '35 17 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp file
        run: |
          echo "Last keepalive: $(date -u)" > .keepalive.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .keepalive.txt
          git commit -m "Keepalive ping"
          git push
